title: jones_the_cat
description: "Ora sta a sentire sorella, non torno a fare quella vita,<br>sono il libero ruspante solitario. E sottolineo libero!"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/dennyverduchi

menu:
  home: ./
  experiences: ./experiences.html
  learning: ./learning_path.html
  machines: ./machines.html
