permalink: /:title

# title: Jones the Cat
# description: "Il mio viaggio di apprendimento dentro la cybersec! E non solo..."
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

cv: /assets/pdf/cv_012025_en.pdf
github: https://github.com/dennyverduchi
linkedin: https://www.linkedin.com/in/denny-verduchi-a446401a4/