permalink: /:title

# title: Jones the Cat
# description: "Il mio viaggio di apprendimento dentro la cybersec! E non solo..."
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

# cv: /assets/pdf/dennyverduchi_cv_2023.pdf

github: https://github.com/dennyverduchi

linkedin: https://www.linkedin.com/in/denny-verduchi-a446401a4/

ctf:
  blue: /pages/ctf/blue
  legacy: /pages/ctf/legacy

learning_path:
  cybersec:
    tcp_ip: /pages/learning_path/cybersec/tcp_ip
    dns: /pages/learning_path/cybersec/dns
    eternalblue: /pages/learning/cybersec/eternalblue
    
hidden_area:
  experiences: /pages/hidden_area/experiences

  finance:
    management: /pages/hidden_area/finance/management
    trading_investing: /pages/hidden_area/finance/trading_investing