title: Jones the Cat
# description: "Ora sta a sentire sorella, non torno a fare quella vita,<br>sono il libero ruspante solitario. E sottolineo libero!"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

cv: /assets/pdf/dennyverduchi_cv_2023.pdf

github: https://github.com/dennyverduchi

linkedin: https://www.linkedin.com/in/denny-verduchi-a446401a4/

ctf:
  blue: /pages/ctf/blue.html
  legacy: /pages/ctf/legacy.html

learning:
  cybersec:
    dns: /pages/learning/cybersec/dns.html
    eternalblue: /pages/learning/cybersec/eternalblue.html

  finance:
    gestione: /pages/learning/finance/gestione.html
    trading-investing: /pages/learning/finance/trading_investing.html