title: Jones the Cat
# description: "Ora sta a sentire sorella, non torno a fare quella vita,<br>sono il libero ruspante solitario. E sottolineo libero!"
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker

cv: /assets/pdf/dennyverduchi_cv_2023.pdf

github: https://github.com/dennyverduchi

linkedin: https://www.linkedin.com/in/denny-verduchi-a446401a4/

machines:
  blue: /pages/machines/blue.html

cybersec:
  dns: /pages/cybersec/dns.html
  eternalblue: /pages/cybersec/eternalblue.html

finance:
  gestione: /pages/finance/gestione.html
  trading-investing: /pages/finance/trading_investing.html